### PR TITLE
feat(s3): Support for assumeRole

### PR DESCRIPTION
**Pull request by ncknt**
This adds support for assume role to s3. It's using a new `assumeRole` (which could be a role or an ARN) and `assumeRoleAccountId` which is used when `assumeRole` is not an ARN.

This implements what the `--assume-role` is meant for in Halyard (currently doesn't do anything): https://www.spinnaker.io/reference/halyard/commands/#hal-config-storage-s3-edit. We'll add the `--assume-role-account-id` in Halyard as well.

### CODE REVIEW

**Comment by ncknt** [comment]
@ajordens, @emjburns: could you PTAL? Unsure if we prefer to use `NetflixSTSAssumeRoleSessionCredentialsProvider` or the newer `STSAssumeRoleSessionCredentialsProvider.Builder`.

**Comment by robzienert** [comment]
We want to use the `Netflix...` one. Better to be consistent, then if we want to change the behavior of assume role, we only need to do it in one place.

**Comment by robzienert** [comment]
Do we still want to merge this? PR has conflicts.

**Comment by ncknt** [comment]
Let me take a look...

**Comment by ncknt** [comment]
This PR was relying on `clouddriver-aws` which is no longer a dependency since Spring Boot 2 clean up. Re-adding it doesn't seem fun (kork-bom?). I'll check if that's still needed, obviously we've been working around it until now.

**Comment by ncknt** [comment]
It is not currently needed. Closing the PR. I'll open a new one if this comes up again.

**Pull request closed without merging**
