### PR TITLE
feat(MPTv2): Adds list by decorated id for artifact support.

### PR DESCRIPTION
**Pull request by jtk54**

### CODE REVIEW

**Comment by ajordens** [comment]
FWIW I think `/listIds` is a bit of an odd looking endpoint and collides with the general `/{id}`.

Wherever possible, we should be trying to not repeat the sins of our past.

For example, in this case I think there's an opportunity to just add another parameter to `list()` and return values of the form:
```
[
  {id: "id1"},
  {id: "id2"}
]
```

rather than:
```
[
  "id1",
  "id2"
]
```

Thoughts?

**Comment by ajordens** [comment]
(late feedback -- I missed the original notification that this came through()

**Comment by jtk54** [comment]
I think so as well in hindsight. Currently this is a useful debugging tool but I agree this could be merged into the existing endpoint to make it a bit more reasonable. We're still mid-execution with a lot of this stuff so we can fix it up as we go.

**Comment by ajordens** [comment]
Thanks, appreciate it getting tidied up at some point.

**Pull request merged**
