### PR TITLE
Pins version of spinnaker-dependencies manifest file

### PR DESCRIPTION
**Pull request by cfieber**
Uses the new functionality in the spinnaker-gradle-project for pinning the version

### CODE REVIEW

**Comment by ajordens** [comment]
Can you make it 0.19.0, it's been fixed in that version.

**Comment by cfieber** [comment]
This pins the dependencies (current behaviour was to pick up latest.release all the time)

Can override at the command-line (`./gradlew build -PdependenciesVersion=latest.release`) which will allow for developing a test suite that we can run after publishing a new version of spinnaker-dependencies

**Comment by cfieber** [comment]
going to look at rolling this block back into the gradle plugin instead of C&P'ing it everywhere

**Comment by cfieber** [comment]
@spinnaker/reviewers FYI - version of the spinnaker-dependencies manifest is now managed this way per project, will apply this change across all the other projects

**Pull request merged**
