### PR TITLE
prevent creation of pipelines with duplicate names

### PR DESCRIPTION
**Pull request by anotherchrisberry**
cc @spinnaker/reviewers

### CODE REVIEW

**Comment by anotherchrisberry** [comment]
@tomaslin or @ajordens PTAL

**Comment by ajordens** [comment]
Pipeline strategies likely need similar treatment.

The rename operation might also let through a duplicate ... it's probably also gated in the UI tho.

**Comment by anotherchrisberry** [comment]
@ajordens Good call. All these operations are gated in the UI, but that won't prevent a race condition (or stale browser data) from letting a duplicate through.

I've updated the PR to check on strategy saves and both rename operations.

**Comment by ajordens** [comment]
LGTM

**Pull request merged**
