### PR TITLE
Support rudimentary Application sorting (w/ pageSize)

### PR DESCRIPTION
**Pull request by ajordens**
Simple algorithm based on:
- strength of match (ie. number of characters matched between search criteria and value)
- position of match (higher scores if match occurs at start of value)

### CODE REVIEW

**Comment by cfieber** [comment]
I would like the ability to 'promote' my application causing it to be featured above the fold in search results.

**Comment by ajordens** [comment]
Started out by just wanting to support `pageSize` but got side tracked by the previous search behavior being overly minimal (ie. just a .contains() ... no sorting).

This change introduces a fairly simple algorithm (_that might not work for everybody_) but at least makes an attempt to sort by strength of match.

**Comment by ajordens** [comment]
$5 per 24hr promotion @cfieber

**Comment by anotherchrisberry** [comment]
Seems like we'd want to weigh the `name` attribute more heavily than others if it's present when determining sort order, but that might clutter the code quite a bit.

LGTM

**Pull request merged**
