### PR TITLE
fix(Pipeline template/front50): Bug fix 6340

### PR DESCRIPTION
**Pull request by pemmasanikrishna**
Issue: [6340](https://github.com/spinnaker/spinnaker/issues/6340)

When the tag is passed from the pipeline template, currently it's getting persisted without getting validated. The current fix has the first priority to the tag passed explicitly via request param, if it's not present, then it considers the one given in the template if any.

### CODE REVIEW

**Comment by pemmasanikrishna** [comment]
@ajordens @KeisukeYamashita can you please look into this

**Comment by mattgogerly** [comment]
@Mergifyio update

**Comment by mattgogerly** [comment]
> @mattgogerly is not allowed to run commands

Brutal.. @pemmasanikrishna please fetch upstream

**Comment by pemmasanikrishna** [comment]
@mattgogerly  done

**Review by mattgogerly — APPROVED** [review]

**Comment by mattgogerly** [comment]
@Mergifyio update

**Pull request merged**
