### PR TITLE
fix(core): correctly save traffic guard configurations

### PR DESCRIPTION
**Pull request by anotherchrisberry**
Did some actual testing this time around

### CODE REVIEW

**Comment by anotherchrisberry** [comment]
@spinnakerbot cherry-pick 1.12

**Comment by anotherchrisberry** [comment]
@jtk54 I hear you are good at cherry picking, do you know what I'm doing wrong here?

**Comment by jtk54** [comment]
I think this change won't cleanly apply to the 1.12 branch so you have to manually try to do the cherry-pick locally and resolve the conflicts :(

Works kinda like rebase though shouldn't be too bad unless someone did a major refactor or something.

**Comment by jtk54** [comment]
https://github.com/spinnaker/front50/pull/450

**Pull request merged**
