### PR TITLE
fix(azure storage container): update permission to Private

### PR DESCRIPTION
**Pull request by ishagarg01**
Front50 to switch off Public access on Azure Blob Containers #5892

Issue Raised for the same #5892

### CODE REVIEW

**Comment by e96wic** [comment]
Hey @IshaGarg2504, thank you for the fix. If possible, you could add some log output in the catch block to the error is not silent. I don't really know the codebase very well, but maybe it makes sense to even throw the error again.

**Comment by zhouchong90** [comment]
Please get this merged!! We have a same issue where our organization prohibited the public access on the container. It doesn't need the public access either since it already has the master key.

**Comment by zhouchong90** [comment]
Oh. btw, these 4 lines doesn't need to exist in my opinion. It should leave the setting to user to configure it on the cloud themselves. I'm concerned that sometimes Azure might prevent clients from changing the access level, which will go to the catch block and return null.

BlobContainerPermissions permissions = new BlobContainerPermissions();
        permissions.setPublicAccess(BlobContainerPublicAccessType.CONTAINER);
        permissions.setPublicAccess(BlobContainerPublicAccessType.OFF);
        blobContainer.uploadPermissions(permissions);

**Comment by robzienert** [comment]
Tests are failing. Can you update?

**Comment by robzienert** [comment]
Will merge when things are passing.

**Comment by pedrohdz** [comment]
@e96wic, @robzienert, @zhouchong90,

I implemented a slightly different approach in the following PR:

- https://github.com/spinnaker/front50/pull/1018

The idea is to leave the permissions alone on existing storage containers.  This would allow for backwards compatibility, not locking out front50.  It also allows for users to specify their own permissions when they create the storage container outside of Spinnaker.

The change also defaults to making the storage container private, a sane default IHMO.

**Comment by jkschneider** [comment]
Duplicate of #1018

**Pull request closed without merging**
