### PR TITLE
fix(Pipeline_template/front50): Typo in validation message

### PR DESCRIPTION
**Pull request by pemmasanikrishna**
Typo fix

### CODE REVIEW

**Comment by mattgogerly** [comment]
@pemmasanikrishna thanks for this - please update your commit to follow the correct convention

**Comment by pemmasanikrishna** [comment]
@mattgogerly could you please suggest what needs to be updated to what

**Comment by mattgogerly** [comment]
> @mattgogerly could you please suggest what needs to be updated to what

Your first commit needs to be of the format type(component): message

e.g. fix(pipelineTemplates): fix typo in error message

**Comment by pemmasanikrishna** [comment]
@mattgogerly done

**Review by mattgogerly — APPROVED** [review]

**Review by dbyron-sf — APPROVED** [review]

**Pull request merged**
