### PR TITLE
fix(migrator): GCS to SQL migrator APPLICATION_PERMISSION objectType fix

### PR DESCRIPTION
**Pull request by christosarvanitis**
Previous implementation was not correctly distinguishing between APPLICATION and APPLICATION_PERMISSION metadata leading to a migrator deserialisation issue for GCS to SQL Front50 migration.

This PR fixes this with a small refactor. 

Fixes https://github.com/spinnaker/spinnaker/issues/6957

### CODE REVIEW

**Review by ovidiupopa07 — APPROVED** [review]

**Review by jasonmcintosh — APPROVED** [review]
I'm good with this ;) Should enable every one on GCS to move to SQL :P then get GCS/S3 support disabled for storage (and docs updated for this) long term!!

**Comment by christosarvanitis** [comment]
@jasonmcintosh would you consider backporting this fix?

**Comment by jasonmcintosh** [comment]
Yeah given that migration is completely broken for GCS to SQL... I'm good with this.  

@mergifyio backport release-1.30.x release-1.31.x  release-1.32.x release-1.33.x release-1.34.x

**Comment by jasonmcintosh** [comment]
https://github.com/Mergifyio backport release-1.30.x release-1.31.x release-1.32.x release-1.33.x release-1.34.x

**Pull request merged**
